<?php
$currentCustomerId= Mage::getSingleton('customer/session')->getCustomer()->getId();
$post = $this->viewOnePost();


var_dump((string)$this->getOnePost($params));


?>

<?php if(isset($post->post_id)) :?>
<div>

    <h1><?=$post->headline?></h1>

    <?php if($post->photo_path != null):?>
        <div >
            <img src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>/media/uploads/<?=$post->photo_path?>"  width="500" title="<?=$post->headline?>">
        </div>
    <?php endif;?>

    <p><?=$post->text;?></p>
    <p>Author: <b><?=$post->author_id ?> </b> , Added at: <b><?=$post->created_at; //date_format($post->created_at, 'Y-m-d H:i:s') ?></b></p>
    <p>
        <?php if(Mage::getSingleton('customer/session')->isLoggedIn() && $currentCustomerId == $post->author_id): ?>

            <b><a href="<?=Mage::getBaseUrl('web')?>blog/post/edit/id/<?=$post->post_id?>">Edit</a></b>

            <form action="<?=Mage::getBaseUrl('web')?>blog/post/delete/id/<?=$post->post_id?>" method="post">
                <input type="hidden" name="delete" value="<?=$post->post_id?>">
                <input type="submit" value="delete">
            </form>

        <?php endif; ?>
    </p>
</div>

<?php endif;?>
