<?php
$binded_products = $this->getBindedProducts();

?>


<?php if(empty($binded_products)): ?>
<div class="block block-sidebar">
    <div class="block-title">
        <strong>
            BINDED PRODUCT
        </strong>
    </div>

    <div class="block-content">
        <?php foreach($binded_products as $product): ?>
            <h2 class="product-name"><?=$product->getName(); ?></h2>
            <div>
                <a href="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $product->getUrlKey() . '.html'?>">
                    <img src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>catalog/product/<?=$product->getImageUrl();?>"  width="100" title="<?=$product->getName()?>">
                </a>
            </div>

            <?=$this->getPriceHtml($product,true)?>

            <p><?=$product->getDescription(); ?> </p>
            <p><?=$product->getProductId(); ?> </p>
            <p><?=$product->getProductUrl(); ?> </p>

            <?php endforeach; ?>
    </div>
</div>

<?php endif; ?>


