<?php


?>

<script type="text/javascript">
    //<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    //            productAddToCartForm.submit = function(button, url) {
    //                if (this.validator.validate()) {
    //                    var form = this.form;
    //                    var oldUrl = form.action;
    //
    //                    if (url) {
    //                       form.action = url;
    //                    }
    //                    var e = null;
    //                    try {
    //                        this.form.submit();
    //                    } catch (e) {
    //                    }
    //                    this.form.action = oldUrl;
    //                    if (e) {
    //                        throw e;
    //                    }
    //
    //                    if (button && button != 'undefined') {
    //                        button.disabled = true;
    //                    }
    //                }
    //            }.bind(productAddToCartForm);
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
                form.action = url;
            }
            var e = null;
//Start of our new ajax code
            if(!url){
                url = jQuery('#product_addtocart_form').attr('action');
            }
            var data = jQuery('#product_addtocart_form').serialize();
            data += '&isAjax=1';
            jQuery('#ajax_loader').show();
            try {
                console.log('works!');
                jQuery.ajax({
                    url: url,
                    dataType: 'json',
                    type : 'post',
                    data: data,
                    success: function(data){
                        jQuery('#ajax_loader').hide();
                        alert(data.status + ": " + data.message);
                        console.log('remove gif');
                    }
                });
                console.log('end');
            } catch (e) {
            }
//End of our new ajax code
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }

            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
    //]]>
</script>
