<?php
$currentCustomerId= Mage::getSingleton('customer/session')->getCustomer()->getId();
$post = $this->viewOnePost();
?>

<?php if(isset($post)) :?>
        <div>

            <h1><?=$post->getHeadline()?></h1>

            <?php if($post->getPhotoPath() != null):?>
                <div>
                    <img src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?><?=$post->getPhotoPath()?>" width="500" title="<?=$post->getHeadline()?>">
                </div>
            <?php endif;?>

            <p><?=$post->getText()?></p>
            <p>Author: <b><?=$post->getFullname() ?> </b> , Added at: <b><?=$post->getCreatedAt(); //date_format($post->created_at, 'Y-m-d H:i:s') ?></b></p>
            <p>
                <?php if(Mage::getSingleton('customer/session')->isLoggedIn() && $currentCustomerId == $post->getAuthorId()): ?>

                    <b><a href="<?=Mage::getBaseUrl('web')?>blog/post/edit/id/<?=$post->getPostId()?>">Edit</a></b>

                    <form action="<?=Mage::getBaseUrl('web')?>blog/post/delete/id/<?=$post->getPostId()?>" method="post">
                        <input type="hidden" name="delete" value="<?=$post->getPostId()?>">
                        <input type="submit" value="delete">
                    </form>

                <?php endif; ?>
            </p>
        </div>

<?php endif;?>

